src/references/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('create_group/', views.create_group, name="create_group"),
    path('submit_url/<int:pk>/', views.submit_url, name="submit_url"),
    path('api/', views.submit_url_api, name="submit_url_api"),
    path('view/<int:pk>/', views.view_group, name="view_group"),
    path('view/<int:pk>/adduser/', views.add_user_to_group, name="add_user_to_group"),
    path('view/<int:pk>/<int:reference>/', views.view_references, name="view_reference"),
    path('view/<int:pk>/<int:reference>/edit/', views.edit_references, name="edit_references"),
    path('view/<int:pk>/<int:reference>/upload/', views.uploadPDFToReference, name="upload_to_reference"),
    path('add/<int:pk>/', views.add, name="add"),
    path('add/<int:pk>/<int:template>/', views.add_template, name="add_template"),
    path('upload/<int:pk>/', views.uploadReference, name="upload"),
    path('upload_bib/<int:group>/', views.upload_bib, name="upload_bib"),
    path('delete/<int:reference>/', views.delete_reference, name="delete_reference"),
    path('export/<int:pk>/export.bib', views.export, name="export"),
    path('search/', views.search, name="search"),
    path('key/', views.view_API_key, name="key"),
    path('view_404', views.view_404, name="view_404"),
    path('', views.index, name="home")
]

src/syncref/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('references.urls'))
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/references/models.py
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.db import models


class Group(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    admin = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class GroupMembership(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + " is a member of " + self.group.name


class Reference(models.Model):
    name = models.CharField(max_length=200)
    bibtex_dump = JSONField()
    created = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    fulltext = models.TextField(default="", null=True)

    def __str__(self):
        return self.name


class ReferenceType(models.Model):
    name = models.CharField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ReferenceField(models.Model):
    name = models.CharField(max_length=200)
    referenceType = models.ForeignKey(ReferenceType, on_delete=models.CASCADE)

    def __str__(self):
        return self.referenceType.name + " " + self.name


class ReferenceFile(models.Model):
    pdf = models.FileField(upload_to='papers')
    reference = models.ForeignKey(Reference, on_delete=models.CASCADE)

    def __str__(self):
        return "PDF of " + self.reference.name


class APIKey(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    key = models.CharField(max_length=32, unique=True)

src/references/forms.py
from django import forms
from .models import ReferenceFile


class ReferenceUpload(forms.Form):
    pdf = forms.FileField()

src/references/views.py
import json
import re
import secrets

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.postgres.search import (SearchQuery, SearchRank,
                                            SearchVector)
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from habanero import cn

from .bibparser import bib2py, py2bib
from .dublincore import parse_meta, url2doi
from .forms import ReferenceUpload
from .grobextract import ExtractionError, content_negotiation, extract
from .models import (APIKey, Group, GroupMembership, Reference, ReferenceField,
                     ReferenceFile, ReferenceType)


@never_cache
def index(request):
    """View to handle the root directory of the website. If the user is logged
    in, then it is the app home page. If the user is not logged in, then a
    landing page is shown.

    Args:
        request (request): A handle to the request

    Returns:
        render: Renders the specified template
    """
    if request.user.is_authenticated:
        groups = [i.group for i in GroupMembership.objects.filter(
            user=request.user)]
        references = []
        for group in groups:
            references += Reference.objects.filter(group=group)
        return render(request, "references/app.html", {
            "groups": groups,
            "references": references
            })
    else:
        return render(request, "references/index.html")


def signup(request):
    """A view to handle the user registration process

    Args:
        request (request): A handle to the request

    Returns:
        render: Renders the registration form
        redirect: Redirects the user to the home page
    """
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            if settings.REQUIRE_ADMIN_AUTH:
                user.is_active = False
                messages.info(request, "You account has been registered. "
                                       "An admin is required to authorise it")
            user.save()
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "references/signup.html", {
        "form": form,
        })


def login(request):
    """A view to handle the login process

    Args:
        request (request): A handle to the request

    Returns:
        render: Renders the login form
        redirect: Redirects the user to the home page
    """
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return redirect("home")
        else:
            messages.error(request, "Invalid Credentials")
    return render(request, "references/login.html")


@login_required
def create_group(request):
    """A view to allow the user to create a group

    Args:
        request (request): A handle to the request

    Returns:
        render: Renders the group creation form
    """
    if request.method == "POST":
        name = request.POST["name"]
        description = request.POST["description"]
        group = Group(name=name, description=description, admin=request.user)
        group.save()
        membership = GroupMembership(group=group, user=request.user)
        membership.save()
        return redirect("view_group", pk=group.pk)
    return render(request, "references/create_group.html",{
        "groups": [i.group for i in GroupMembership.objects.filter(
            user=request.user)]
    })


@login_required
@never_cache
def view_group(request, pk):
    """A view to allow the user to view a specified group

    Args:
        request (request): A handle to the request
        pk (int): The promary key of the group

    Raises:
        PermissionDenied: Raised when a user who is not a member of the group
                          tries to access the group

    Returns:
        render: Renders the group information
    """
    group = get_object_or_404(Group, pk=pk)
    if GroupMembership.objects.filter(group=group, user=request.user).exists():
        # Get all references to do with the group
        references = Reference.objects.filter(group=group)
        return render(request, "references/group.html", {
            "group": group,
            "references": references,
            "groups": [i.group for i in GroupMembership.objects.filter(
                user=request.user)]

        })
    else:
        raise PermissionDenied


@login_required
def add(request, pk):
    """A view to allow the user to add a reference to a group

    Args:
        request (request): A handle to the request
        pk (int): The primary key of the group

    Raises:
        PermissionDenied: Raised when a user who is not a member of the group
                          tries to access the group

    Returns:
        render: The form to allow the addition of a reference
        redirect: Redirects the user to the group home page upon successfull
                  entry of a reference
    """
    group = get_object_or_404(Group, pk=pk)
    if GroupMembership.objects.filter(group=group, user=request.user).exists():
        if request.method == 'POST':
            pairs = {}
            for key in request.POST:
                if "key" in key:
                    key_number = re.findall(r"[0-9]*$", key)[0]
                    for value in request.POST:
                        if "value" in value:
                            val_number = re.findall(r"[0-9]*$", value)[0]
                            if val_number == key_number:
                                pairs[request.POST[key].casefold()] = request.POST[value]

                                break
            # TODO ensure proper ID TYPE etc
            pairs["ENTRYTYPE"] = request.POST["type"]
            pairs["ID"] = request.POST["name"]
            reference = Reference(name=request.POST["name"],
                                  bibtex_dump=[pairs],
                                  group=group)
            reference.save()
            return redirect("view_group", pk=group.pk)
        else:
            return render(request, "references/add.html", {
                "pk": group.pk,
                "groups": [i.group for i in GroupMembership.objects.filter(
                    user=request.user)],
                "types": ReferenceType.objects.all()
            })
    else:
        raise PermissionDenied


@login_required
def edit_references(request, pk, reference):
    """A view to allow the user to add a reference to a group

    Args:
        request (request): A handle to the request
        pk (int): The primary key of the group

    Raises:
        PermissionDenied: Raised when a user who is not a member of the group
                          tries to access the group

    Returns:
        render: The form to allow the addition of a reference
        redirect: Redirects the user to the group home page upon successfull
                  entry of a reference
    """
    group = get_object_or_404(Group, pk=pk)
    if GroupMembership.objects.filter(group=group, user=request.user).exists() and get_object_or_404(Reference, pk=reference).group == group:
        if request.method == 'POST':
            pairs = {}
            for key in request.POST:
                if "key" in key:
                    key_number = re.findall(r"[0-9]*$", key)[0]
                    for value in request.POST:
                        if "value" in value:
                            val_number = re.findall(r"[0-9]*$", value)[0]
                            if val_number == key_number:
                                pairs[request.POST[key].casefold()] = request.POST[value]
                                break
                                # Forgive me for the indentation
            pairs["ID"] = request.POST["name"]
            pairs["ENTRYTYPE"] = request.POST["type"]
            reference_object = Reference.objects.get(pk=reference)
            reference_object.name = request.POST["name"]
            reference_object.bibtex_dump = [pairs]
            reference_object.group = group
            reference_object.save()
            return redirect("view_reference", pk=group.pk, reference=reference)
        else:
            return render(request, "references/add.html", {
                "pk": group.pk,
                "groups": [i.group for i in GroupMembership.objects.filter(user=request.user)]

            })
    else:
        raise PermissionDenied


@login_required
def uploadReference(request, pk):
    """Upload a PDF to be parsed for the metadata
    
    Args:
        request (request): A handle ot the request
        pk (int): The pk of the group to upload to
    
    Raises:
        PermissionDenied: The user is not a member of the group they are
        uploading to
    
    Returns:
        redirect: A redirect to the uploaded and parsed PDF
    """
    group = get_object_or_404(Group, pk=pk)
    if GroupMembership.objects.filter(group=group, user=request.user).exists():
        if request.method == 'POST':

src/references/templates/references/add.html
{% extends "references/base.html" %}
{% load static %}

{% block body %}
<h1>Add citation</h1>
<ul class="tabs" data-deep-link="true" data-update-history="true" data-deep-link-smudge="true" data-deep-link-smudge-delay="500" data-tabs id="method-chooser">
    <li class="tabs-title is-active"><a href="#panel1" aria-selected="true"><i class="fi-paperclip"></i> PDF Upload</a></li>
    <li class="tabs-title"><a data-tabs-target="panel2" href="#panel2"><i class="fi-link"></i> URL Entry</a></li>
    <li class="tabs-title"><a data-tabs-target="panel3" href="#panel3"><i class="fi-pencil"></i> Manual Entry</a></li>
</ul>
<div class="tabs-content" data-tabs-content="method-chooser">
    <div class="tabs-panel is-active" id="panel1">
        <form method="post" enctype="multipart/form-data" action="{% url 'upload' pk %}">
            {% csrf_token %}
            <label for="pdf" class="">Choose PDF:</label>
            <input type="file" id="pdf" class="" name="pdf">
            <button type="submit" class="button">Upload</button>
        </form>
    </div>
    <div class="tabs-panel" id="panel2">
        <form method="post" action="{% url 'submit_url' pk %}">
            {% csrf_token %}
            <input type="text" name="url" id="url" placeholder="URL" />
            <input type="submit" value="Submit" class="button">
        </form>
    </div>
    <div class="tabs-panel" id="panel3">
        <ul class="dropdown menu" data-dropdown-menu>
            <li>
              <span class="button">Prefill</span>
              <ul class="menu">
                  {% for type in types %}
                    <li><a href="{% url 'add_template' pk type.pk %}#panel3">{{type.name}}</a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
        <form action="{% url 'add' pk %}" method="POST">
            {% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="small-12 medium-6 cell">
                    <input type='text' placeholder='Name' id='name' name="name">
                </div>
                <div class="small-12 medium-6 cell">
                    <input type='text' placeholder='Type' id='type' name="type" value="{{type}}">
                </div>
            </div>
            <div class="container">
                {% block prefilled %}
                    <div class='element grid-x grid-padding-x' id='div_1'>
                        <div class="small-12 medium-6 cell">
                            <input type='text' placeholder='Key' id='key_1' name="key_1">
                        </div>
                        <div class="small-12 medium-6 cell">
                            <input type='text' placeholder='Value' id='value_1' name="value_1">
                        </div>
                    </div>
                {% endblock %}
            </div>
            <div class="grid-x grid-padding-x">
                <div class="small-12 cell">
                    <span class='add button hollow small'><i class="fi-plus"></i> </span> <br>
                </div>
            </div>
            <input type="submit" value="Add Citation" class="button">
        </form>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
    $(document).ready(function(){
        
        // Add new element
        $(".add").click(function(){
            
            // Finding total number of elements added
            var total_element = $(".element").length;
            
            // last <div> with element class id
                var lastid = $(".element:last").attr("id");
                var split_id = lastid.split("_");
                var nextindex = Number(split_id[1]) + 1;
                
                // Adding new div container after last occurance of element class
                $(".element:last").after("<div class='element grid-x grid-padding-x' id='div_"+ nextindex +"'></div>");
                
                // Adding element to <div>
                    $("#div_" + nextindex).append("<div class='small-6 medium-6 cell'><input type='text' placeholder='Key' id='key_"+ nextindex +"' name='key_"+ nextindex +"'></div> <div class='small-5 medium-5 cell'><input type='text' placeholder='Value' id='value_"+ nextindex +"' name='value_"+ nextindex +"' ></div><div class='small-1 cell'><span id='remove_" + nextindex + "' class='remove hollow button alert small'><i class='fi-x'></i></span></div>");
                    
                });
                
                // Remove element
                $('.container').on('click','.remove',function(){
                    
                    var id = this.id;
                    var split_id = id.split("_");
                    var deleteindex = split_id[1];
                    
                    // Remove <div> with id
                        $("#div_" + deleteindex).remove();
                        
                    }); 
                });
            </script>
            
            {% endblock %}

src/references/templates/references/add_template.html
{% extends "references/add.html" %}

{% block prefilled %}

{% for value in fields %}
<div class="element grid-x grid-padding-x" id='div_{{value.1}}'>
    <div class='small-6 medium-6 cell'>
        <input type='text' placeholder='Key' id='key_{{value.1}}' name='key_{{value.1}}' value='{{value.0.name}}'>
    </div>
    <div class='small-5 medium-5 cell'>
        <input type='text' placeholder='Value' id='value_{{value.1}}' name='value_{{value.1}}'>
    </div>
    <div class='small-1 cell'>
        <span id='remove_{{value.1}}' class='remove hollow button alert small'>
            <i class='fi-x'></i>
        </span>
    </div>
</div>
{% endfor %}
{% endblock %}

src/references/templates/references/app.html
{% extends "references/base.html" %}
{% load static %}

{% block body %}    
    <div class="container">
        <h1>Your references</h1>
        <div class="grid-x">
            {% for reference in references %}
                <div class="cell small-12">
                    <div class="card">
                        <div class="card-divider">
                            <a href="{% url 'view_reference' reference.group.pk reference.pk %}">
                                <h6>{{reference.name}}</h6> 
                            </a>
                        </div>            <div class="card-section">
                            <p>{{reference.bibtex_dump.0.author}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>    
{% endblock %}

src/references/templates/references/create_group.html
{% extends "references/base.html" %}
{% load static %}

{% block body %}
    <h1>Create Group</h1>
    <form method="post" action="{% url 'create_group' %}">
        <div class="grid-x">
            {% csrf_token %}
            <div class="small-12 medium-6 cell">
                <input type="text" name="name" id="name" placeholder="Name"/>
            </div>
        </div>
        <div class="grid-x">
            <div class="small-12 medium-6 cell">
                <textarea name="description" id="description" placeholder="Description"></textarea>
            </div> 
        </div>
        <input type="submit" value="Submit" class="button">
    </form>
{% endblock %}

src/references/templates/references/group.html
{% extends "references/base.html" %}
{% load static %}
{% block breadcrumbs %}
<ul class="breadcrumbs">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li>{{group.name}}</li>
</ul>
{% endblock %}

{% block body %}
    <p>
        <h1 class="text-3xl">{{group.name}}</h1>
            {{group.description}}
        
    </p>
    <p>
        <div class="button-group">
            <a href="{% url 'add' group.pk %}" class="button success">Add citation</a>
            <a href="{% url 'export' group.pk %}" class="button">Export BibTeX file</a>

        </div>
    </p>
    <p>
         {% for reference in references %}
                <div class="cell small-12">
                    <div class="card">
                        <div class="card-divider">
                            <a href="{% url 'view_reference' reference.group.pk reference.pk %}">
                                <h6>{{reference.name}}</h6> 
                            </a>
                        </div>            <div class="card-section">
                            <p>{{reference.bibtex_dump.0.author}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </p>
    
    <p>
    <div class="grid-x grid-margin-x" data-equalizer data-equalize-on="medium" id="options">
        <div class="small-12 medium-6 cell" >
            <div class="callout" data-equalizer-watch>
                Add user to the group:
                <form method="post" action="{% url 'add_user_to_group' group.pk %}">
                    {% csrf_token %}
                    <div class="grid-x grid-margin-x">
                        <div class="medium-6 cell">
                            <label>Username
                                <input type="text" name="user">
                            </label>
                        </div>
                        <div class="medium-12 cell">
                            <input type="submit" value="Add user" class="button">
                        </div>
                    </div>
                </form>
            </div>

        </div>
        <div class="small-12 medium-6 cell">
            <div class="callout" data-equalizer-watch>
                Upload .bib file:
                <form method="post" enctype="multipart/form-data" action="{% url 'upload_bib' group.pk %}">
                    {% csrf_token %}
                    <p><label for="bib">Bib File:</label> <input type="file" name="bib_file" required id="bib"></p>
                </select></p>
                <button type="submit" class="button">Upload</button>
            </form>
            </div>

        </div>
    </div>
        
        
        
    </p>
     
    <!-- <div class="button-group">

        <a href="{% url 'home' %}" class="button">Back</a><a href="{% url 'logout' %}" class="button">Logout</a>
    </div> -->
{% endblock %}

src/references/templates/references/upload.html
{% extends 'references/base.html' %}

{% block body %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p><label for="id_pdf">Pdf:</label> <input type="file" name="pdf" required id="id_pdf"></p>
</select></p>
    <button type="submit">Upload</button>
  </form>


  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

src/references/templates/references/view_reference.html
{% extends "references/base.html" %}
{% load static %}

{% block breadcrumbs %}
<ul class="breadcrumbs">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'view_group' reference.group.pk %}" >{{reference.group.name}}</a></li>
    <li>{{reference.name}}</li>
</ul>
{% endblock %}

{% block body %}
<h1>{{reference.name}}</h1>
<hr>
<ul class="tabs" data-tabs id="mode">
    <li class="tabs-title is-active"><a href="#panel1" aria-selected="true"><i class="fi-eye"></i> View Reference</a></li>
    <li class="tabs-title"><a data-tabs-target="panel2" href="#panel2"><i class="fi-pencil"></i> Edit Citation</a></li>
</ul>
<div class="tabs-content" data-tabs-content="mode">
    <div class="tabs-panel is-active" id="panel1">
        <br>
        {% for key, value in bibtex_py.items %}
        <b>{{key}}</b> - {{value.0}}<br>
        {% endfor %}
        <br>
<code class="code-block" id="code-block">{{bibtex}}<button class="button small float-right hollow  copy" data-clipboard-target="#code-block" id="copy"><i class="fi-clipboard-notes"></i> Copy</button></code>
<!-- <button class="button" data-clipboard-target="#code-block" id="copy">Copy</button> -->
        Files:
        <ul class="accordion" data-accordion data-allow-all-closed="true">
            {% for file in files %}
                <li class="accordion-item" data-accordion-item>
                    <a href="{{file.pdf.url}}" class="accordion-title">{{file.pdf.name}}</a>
                    <div class="accordion-content" data-tab-content id="exclusive">
                        <embed src="{{file.pdf.url}}" type="application/pdf" width="100%" style="min-height:90vh" />
                    </div>
                </li>
              {% endfor %}
          </ul>
    </div>
    <div class="tabs-panel" id="panel2">
        <h5>Edit fields:</h5>
        <form action="{% url 'edit_references' reference.group.pk reference.pk %}" method="POST">
            {% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="small-12 medium-6 cell">
                    <label>Name
                        <input type='text' placeholder='Name' id='name' name="name" value="{{name}}">
                    </label>
                </div>
                <div class="small-12 medium-6 cell">
                    <label>
                        Entry Type
                        <input type='text' placeholder='Type' id='type' name="type" value="{{entrytype}}">
                    </label>
                </div>
            </div>
            <div class="grid-x grid-padding-x">
                <div class="small-12 medium-6 cell">
                    Keys:
                </div>
                <div class="small-12 medium-6 cell">
                    Values:
                </div>
            </div>
            <div class="container">
                {% for key, value in bibtex_py.items %}
                <div class="element grid-x grid-padding-x" id='div_{{value.1}}'>
                    <div class='small-6 medium-6 cell'>
                        <input type='text' placeholder='Key' id='key_{{value.1}}' name='key_{{value.1}}' value='{{key}}'>
                    </div>
                    <div class='small-5 medium-5 cell'>
                        <input type='text' placeholder='Value' id='value_{{value.1}}' name='value_{{value.1}}' value='{{value.0}}'>
                    </div>
                    <div class='small-1 cell'>
                        <span id='remove_{{value.1}}' class='remove hollow button alert small'>
                            <i class='fi-x'></i>
                        </span>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="grid-x grid-padding-x">
                <div class="small-12 cell">
                    <span class='add button hollow small'><i class="fi-plus"></i> </span> <br>
                </div>
            </div>
            <input type="submit" value="Update" class="button">
        </form>
        <div class="grid-x grid-margin-x" data-equalizer data-equalize-on="medium" id="options">
        <div class="small-12 cell" >
            <div class="callout" data-equalizer-watch>
                Upload Reference:
                <form method="post" enctype="multipart/form-data" action="{% url 'upload_to_reference' reference.group.pk reference.pk %}">
            {% csrf_token %}
            <p><label for="id_pdf">Pdf:</label> <input type="file" name="pdf" required id="id_pdf"></p>
        </select></p>
        <button type="submit" class="button">Upload</button>
        </form>
            </div>

        </div>
    </div>
                     <a href="{% url 'delete_reference' reference.pk %}" class="button alert">DELETE REFERENCE</a>


    
</div>
</div>
<!-- <br><a href="{% url 'view_group' reference.group.pk%}">Back</a> -->
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
<script>
    var clipboard = new ClipboardJS('#copy');
    clipboard.on('success', function(e) {
        console.info('Action:', e.action);
        console.info('Text:', e.text);
        console.info('Trigger:', e.trigger);
        $('#copy').html('<i class="fi-like"></i>  Copied')
        e.clearSelection();
    });
    
    $(document).ready(function(){        
        // Add new element
        $(".add").click(function(){
            
            // Finding total number of elements added
            var total_element = $(".element").length;
            
            // last <div> with element class id
                var lastid = $(".element:last").attr("id");
                var split_id = lastid.split("_");
                var nextindex = Number(split_id[1]) + 1;
                
                // Adding new div container after last occurance of element class
                $(".element:last").after("<div class='element grid-x grid-padding-x' id='div_"+ nextindex +"'></div>");
                
                // Adding element to <div>
                    $("#div_" + nextindex).append("<div class='small-6 medium-6 cell'><input type='text' placeholder='Key' id='key_"+ nextindex +"' name='key_"+ nextindex +"'></div> <div class='small-5 medium-5 cell'><input type='text' placeholder='Value' id='value_"+ nextindex +"' name='value_"+ nextindex +"' ></div><div class='small-1 cell'><span id='remove_" + nextindex + "' class='remove hollow button alert small'><i class='fi-x'></i></span></div>");
                    
                });
                
                // Remove element
                $('.container').on('click','.remove',function(){
                    
                    var id = this.id;
                    var split_id = id.split("_");
                    var deleteindex = split_id[1];
                    
                    // Remove <div> with id
                        $("#div_" + deleteindex).remove();
                        
                    }); 
                });
            </script>
            
            {% endblock %}